// The two targets, and the options that reach them.
//
// Run from the package directory: `npm test`. Both targets are real here — the JavaScript one compiles
// and runs off the assets in this package, and the WebAssembly one compiles, links and runs through
// `@live-codes/clang-wasm`'s toolchain, which needs no baseUrl in Node either.
import assert from 'node:assert/strict';
import test from 'node:test';

import { createCompiler, targets, TARGETS } from '@live-codes/nim-wasm';

const EXPECTED = [
	'Hello, browser!',
	'i = 0',
	'i = 1',
	'i = 2',
	'i = 3',
	'i = 4',
	'sorted: @[1, 1, 2, 3, 4, 5, 6, 9]',
	'5! = 120'
].join('\n');

// Everything both backends can run, so the two results are comparable.
const SHARED = `import strformat, algorithm

let name = "browser"
echo "Hello, ", name, "!"

for i in 0..4:
  echo &"i = {i}"

let xs = @[3, 1, 4, 1, 5, 9, 2, 6]
echo "sorted: ", xs.sorted

proc factorial(n: int): int =
  if n <= 1: 1 else: n * factorial(n-1)
echo "5! = ", factorial(5)
`;

test('the targets are the two the package documents', () => {
	assert.deepEqual(targets, ['wasm', 'js']);
	assert.equal(TARGETS.WASM, 'wasm');
	assert.equal(TARGETS.JS, 'js');
});

test('an unknown target is rejected with the list of valid ones', async () => {
	await assert.rejects(
		() => createCompiler({ target: 'asm' }),
		/Unknown target[\s\S]*wasm, js/
	);
});

test('wasm: compiles, links and runs, with the result shape', async () => {
	const compiler = await createCompiler({ target: 'wasm' });
	const result = await compiler.run(SHARED);

	assert.deepEqual(result.errors, []);
	assert.equal(result.stdout, `${EXPECTED}\n`);
	assert.equal(result.stderr, '');
	assert.equal(result.output, `${EXPECTED}\n`);
	assert.equal(result.exitCode, 0);
	assert.ok(result.compileMs > 0);
	assert.ok(result.runMs >= 0);
	assert.equal(compiler.target, 'wasm');
});

test('js: compiles and runs, and hands back the program it ran', async () => {
	const compiler = await createCompiler({ target: TARGETS.JS });
	const result = await compiler.run(SHARED);

	assert.deepEqual(result.errors, []);
	assert.equal(result.output, EXPECTED);
	assert.equal(result.exitCode, 0);
	// One readable file, which is the whole reason the target is useful to a compiled-code viewer.
	assert.match(result.compiledCode, /Generated by the Nim Compiler/);
});

test('js: execute: false compiles without running', async () => {
	const compiler = await createCompiler({ target: 'js' });
	const result = await compiler.run(`echo "should not appear"\n`, '', { execute: false });

	assert.deepEqual(result.errors, []);
	assert.equal(result.exitCode, null);
	assert.equal(result.runMs, null);
	assert.equal(result.output, '');
	// The program is there and was not run. Its text arrives as character codes, so the check is for the
	// part of the file that is always literal.
	assert.match(result.compiledCode, /Generated by the Nim Compiler/);
});

test('a Nim error is reported as diagnostics, and nothing runs', async () => {
	const compiler = await createCompiler({ target: 'wasm' });
	const result = await compiler.run('let x: int = "not an int"\n');

	assert.equal(result.exitCode, null);
	assert.equal(result.runMs, null);
	assert.ok(
		result.errors.some((line) => /Error:/.test(line)),
		`expected diagnostics, got:\n${result.errors.join('\n')}`
	);
	// Diagnostics come back without colour, since the compiler writes them with it.
	assert.ok(!/\u001b\[/.test(result.errors.join('\n')), 'expected ANSI escapes to be stripped');
});

test('wasm: program output arrives while it is written, not only at the end', async () => {
	const compiler = await createCompiler({ target: 'wasm' });
	const streamed = [];
	const result = await compiler.run(`for i in 0..2: echo i\n`, '', {
		onOutput: (text) => streamed.push(text)
	});

	assert.deepEqual(result.errors, []);
	assert.equal(streamed.join(''), result.stdout);
	assert.match(result.stdout, /0\n1\n2\n/);
});

test('args reach the program', async () => {
	const compiler = await createCompiler({ target: 'wasm', args: ['one'] });
	const program = `import os, strutils
let params = commandLineParams()
echo params.len, ": ", params.join(",")
`;
	assert.equal((await compiler.run(program)).stdout, '1: one\n');
	assert.equal((await compiler.run(program, '', { args: ['a', 'b'] })).stdout, '2: a,b\n');
});

test('compileArgs reach the compiler', async () => {
	const compiler = await createCompiler({ target: 'wasm', compileArgs: ['-d:release2'] });
	// `-d:release2` is a define, so this compiles and the program can see it.
	const result = await compiler.run(`when defined(release2): echo "defined" else: echo "not defined"\n`);
	assert.deepEqual(result.errors, []);
	assert.equal(result.stdout, 'defined\n');
});

test('one compiler keeps working across runs', async () => {
	const compiler = await createCompiler({ target: 'js' });
	assert.equal((await compiler.run('echo "first"\n')).stdout, 'first');
	assert.equal((await compiler.run('echo "second"\n')).stdout, 'second');
	assert.equal((await compiler.run('echo "third"\n')).stdout, 'third');
});

test('the two targets can be used side by side', async () => {
	const [js, wasm] = await Promise.all([
		createCompiler({ target: 'js' }),
		createCompiler({ target: 'wasm' })
	]);
	const results = await Promise.all([js.run('echo "js"\n'), wasm.run('echo "wasm"\n')]);
	assert.equal(results[0].stdout, 'js');
	assert.equal(results[1].stdout, 'wasm\n');
});

test('without a filesystem baseUrl is required, and the error says what to do', async () => {
	const browserEntry = await import('../src/index.js');
	await assert.rejects(
		() => browserEntry.createCompiler({ target: 'js' }),
		/baseUrl is required here[\s\S]*copy-assets/
	);
});
