// The two targets, and the options that reach them.
//
// Run from the package directory: `npm test`. Both targets are real here — the JavaScript one compiles
// and runs off the assets in this package, and the WebAssembly one compiles, links and runs through
// `@live-codes/clang-wasm`'s toolchain, which needs no baseUrl in Node either.
import assert from 'node:assert/strict';
import test from 'node:test';
import vm from 'node:vm';

import { createCompiler, targets, TARGETS } from '@live-codes/nim-wasm';

const EXPECTED = [
	'Hello, browser!',
	'i = 0',
	'i = 1',
	'i = 2',
	'i = 3',
	'i = 4',
	'sorted: @[1, 1, 2, 3, 4, 5, 6, 9]',
	'5! = 120'
].join('\n');

// Everything both backends can run, so the two results are comparable.
const SHARED = `import strformat, algorithm

let name = "browser"
echo "Hello, ", name, "!"

for i in 0..4:
  echo &"i = {i}"

let xs = @[3, 1, 4, 1, 5, 9, 2, 6]
echo "sorted: ", xs.sorted

proc factorial(n: int): int =
  if n <= 1: 1 else: n * factorial(n-1)
echo "5! = ", factorial(5)
`;

test('the targets are the two the package documents', () => {
	assert.deepEqual(targets, ['wasm', 'js']);
	assert.equal(TARGETS.WASM, 'wasm');
	assert.equal(TARGETS.JS, 'js');
});

test('an unknown target is rejected with the list of valid ones', async () => {
	await assert.rejects(
		() => createCompiler({ target: 'asm' }),
		/Unknown target[\s\S]*wasm, js/
	);
});

test('wasm: compiles, links and runs, with the result shape', async () => {
	const compiler = await createCompiler({ target: 'wasm' });
	const result = await compiler.run(SHARED);

	assert.deepEqual(result.errors, []);
	assert.equal(result.stdout, `${EXPECTED}\n`);
	assert.equal(result.stderr, '');
	assert.equal(result.output, `${EXPECTED}\n`);
	assert.equal(result.exitCode, 0);
	assert.ok(result.compileMs > 0);
	assert.ok(result.runMs >= 0);
	assert.equal(compiler.target, 'wasm');
});

test('js: compiles and runs, and hands back the program it ran', async () => {
	const compiler = await createCompiler({ target: TARGETS.JS });
	const result = await compiler.run(SHARED);

	assert.deepEqual(result.errors, []);
	assert.equal(result.output, EXPECTED);
	assert.equal(result.exitCode, 0);
	// One readable file, which is the whole reason the target is useful to a compiled-code viewer.
	assert.match(result.compiledCode, /Generated by the Nim Compiler/);
});

test('js: execute: false compiles without running', async () => {
	const compiler = await createCompiler({ target: 'js' });
	const result = await compiler.run(`echo "should not appear"\n`, '', { execute: false });

	assert.deepEqual(result.errors, []);
	assert.equal(result.exitCode, null);
	assert.equal(result.runMs, null);
	assert.equal(result.output, '');
	// The program is there and was not run. Its text arrives as character codes, so the check is for the
	// part of the file that is always literal.
	assert.match(result.compiledCode, /Generated by the Nim Compiler/);
});

test('a Nim error is reported as diagnostics, and nothing runs', async () => {
	const compiler = await createCompiler({ target: 'wasm' });
	const result = await compiler.run('let x: int = "not an int"\n');

	assert.equal(result.exitCode, null);
	assert.equal(result.runMs, null);
	assert.ok(
		result.errors.some((line) => /Error:/.test(line)),
		`expected diagnostics, got:\n${result.errors.join('\n')}`
	);
	// Diagnostics come back without colour, since the compiler writes them with it.
	assert.ok(!/\u001b\[/.test(result.errors.join('\n')), 'expected ANSI escapes to be stripped');
});

test('wasm: program output arrives while it is written, not only at the end', async () => {
	const compiler = await createCompiler({ target: 'wasm' });
	const streamed = [];
	const result = await compiler.run(`for i in 0..2: echo i\n`, '', {
		onOutput: (text) => streamed.push(text)
	});

	assert.deepEqual(result.errors, []);
	assert.equal(streamed.join(''), result.stdout);
	assert.match(result.stdout, /0\n1\n2\n/);
});

test('args reach the program', async () => {
	const compiler = await createCompiler({ target: 'wasm', args: ['one'] });
	const program = `import os, strutils
let params = commandLineParams()
echo params.len, ": ", params.join(",")
`;
	assert.equal((await compiler.run(program)).stdout, '1: one\n');
	assert.equal((await compiler.run(program, '', { args: ['a', 'b'] })).stdout, '2: a,b\n');
});

test('compileArgs reach the compiler', async () => {
	const compiler = await createCompiler({ target: 'wasm', compileArgs: ['-d:release2'] });
	// `-d:release2` is a define, so this compiles and the program can see it.
	const result = await compiler.run(`when defined(release2): echo "defined" else: echo "not defined"\n`);
	assert.deepEqual(result.errors, []);
	assert.equal(result.stdout, 'defined\n');
});

test('one compiler keeps working across runs', async () => {
	const compiler = await createCompiler({ target: 'js' });
	assert.equal((await compiler.run('echo "first"\n')).stdout, 'first');
	assert.equal((await compiler.run('echo "second"\n')).stdout, 'second');
	assert.equal((await compiler.run('echo "third"\n')).stdout, 'third');
});

test('the two targets can be used side by side', async () => {
	const [js, wasm] = await Promise.all([
		createCompiler({ target: 'js' }),
		createCompiler({ target: 'wasm' })
	]);
	const results = await Promise.all([js.run('echo "js"\n'), wasm.run('echo "wasm"\n')]);
	assert.equal(results[0].stdout, 'js');
	assert.equal(results[1].stdout, 'wasm\n');
});

test('wasm: stdin, stdout and stderr are the real thing', async () => {
	const compiler = await createCompiler({ target: 'wasm' });

	// One read, which is the shape a panel handing over a text box gets.
	const one = await compiler.run(
		`import std/strutils\nlet line = stdin.readLine()\necho "read: ", line.strip()\n`,
		'hello from stdin\n'
	);
	assert.deepEqual(one.errors, []);
	assert.equal(one.stdout, 'read: hello from stdin\n');
	assert.equal(one.exitCode, 0);

	// More than one, which is what a program looping over `stdin.lines` does.
	const many = await compiler.run(
		`var count = 0\nfor line in stdin.lines:\n  inc count\n  echo line\necho "lines: ", count\n`,
		'a\nb\nc\n'
	);
	assert.deepEqual(many.errors, []);
	assert.equal(many.stdout, 'a\nb\nc\nlines: 3\n');

	// No input at all: the end of input is reported rather than waited on.
	const empty = await compiler.run(`echo stdin.readLine()\n`, '');
	assert.equal(empty.exitCode, 1);
	assert.match(empty.stderr, /EOF/);

	// And the two streams are separate, which is what a console panel keys off.
	const both = await compiler.run(`stdout.write("out\\n")\nstderr.write("err\\n")\n`);
	assert.deepEqual(both.errors, []);
	assert.equal(both.stdout, 'out\n');
	assert.equal(both.stderr, 'err\n');
	assert.equal(both.output, 'out\nerr\n');
});

test('the js backend can import the browser modules', async () => {
	const compiler = await createCompiler({ target: 'js' });

	// `lib/js` is on the search path by default, so these resolve. Without it, `import dom` fails with
	// "cannot open file: dom", which reads like a missing module rather than a misplaced one.
	const dom = await compiler.run(
		`import dom
document.title = "Nim was here"
let el = document.createElement("p")
el.innerText = "hello from Nim"
document.body.appendChild(el)
`,
		'',
		{ execute: false }
	);
	assert.deepEqual(dom.errors, []);
	assert.match(dom.compiledCode, /\bdocument\b/);

	// Run against a stand-in page, which is what this target is for.
	const created = [];
	const page = {
		title: '',
		body: { appendChild: (element) => created.push(element) },
		createElement: (tag) => ({ tag, innerText: '' })
	};
	vm.runInNewContext(dom.compiledCode, { document: page, console });
	assert.equal(page.title, 'Nim was here');
	assert.deepEqual(
		created.map((element) => `${element.tag}:${element.innerText}`),
		['p:hello from Nim']
	);

	// jsffi is the general route to anything else on the page.
	const interop = await compiler.run(
		`import jsffi

proc alert(message: cstring) {.importc.}
alert("hello")
`,
		'',
		{ execute: false }
	);
	assert.deepEqual(interop.errors, []);
	assert.match(interop.compiledCode, /alert\(/);
});

test('without a filesystem baseUrl is required, and the error says what to do', async () => {
	const browserEntry = await import('../src/index.js');
	await assert.rejects(
		() => browserEntry.createCompiler({ target: 'js' }),
		/baseUrl is required here[\s\S]*copy-assets/
	);
});

test('dispose releases the compiler, and using it afterwards says so', async () => {
	const compiler = await createCompiler({ target: 'js' });
	assert.equal((await compiler.run('echo "before"\n')).stdout, 'before');

	await compiler.dispose();
	await compiler.dispose(); // and again, which is a no-op rather than an error

	await assert.rejects(() => compiler.run('echo "after"\n'), /has been disposed/);
});

test('disposing one compiler leaves another one working', async () => {
	// Both compile through one shared Clang runtime, which is the case a cached toolchain gets wrong:
	// disposing either would have taken the runtime out from under the other, and the second compiler's
	// headers would have been mounted into a filesystem that already had them.
	const [first, second] = await Promise.all([
		createCompiler({ target: 'wasm' }),
		createCompiler({ target: 'wasm' })
	]);
	assert.equal((await first.run('echo "first"\n')).stdout, 'first\n');

	await first.dispose();

	assert.equal((await second.run('echo "second"\n')).stdout, 'second\n');
	assert.equal((await second.run('echo "still"\n')).stdout, 'still\n');
});

test('the js program is self-sufficient: a console is all it needs to run', async () => {
	const compiler = await createCompiler({ target: 'js' });
	const { compiledCode } = await compiler.run(
		`import strutils\necho "hi, ", "NIM".toLowerAscii, " ", 6 * 7\n`,
		'',
		{ execute: false }
	);

	// This is what makes the target usable as a compiler whose output the caller runs itself: one file,
	// with nothing in it left to resolve.
	assert.doesNotMatch(compiledCode, /^\s*import\s/m, 'expected no module imports');
	assert.doesNotMatch(compiledCode, /\brequire\s*\(/, 'expected no requires');
	assert.doesNotMatch(compiledCode, /\bdocument\b/, 'expected no DOM');

	// A bare context with a console and nothing else is enough to run it.
	const lines = [];
	const sink = (...args) => lines.push(args.join(' '));
	vm.runInNewContext(compiledCode, { console: { log: sink, error: sink, warn: sink } });
	assert.deepEqual(lines, ['hi, nim 42']);
});
